create table if not exists public.guide_step_feedback (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.user_sessions(id) on delete cascade,
  guide_id text not null,
  country text not null,
  problem_type text not null,
  consulate_id text,
  step_id integer not null,
  step_title text not null,
  feedback_type text not null check (feedback_type in ('like', 'dislike')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists guide_step_feedback_session_step_uidx
  on public.guide_step_feedback (session_id, step_id);

create index if not exists guide_step_feedback_guide_idx
  on public.guide_step_feedback (guide_id, step_id, created_at desc);

create index if not exists guide_step_feedback_country_idx
  on public.guide_step_feedback (country, created_at desc);
