create table if not exists public.request_rate_limits (
  id bigint generated by default as identity primary key,
  route_key text not null,
  client_ip text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists request_rate_limits_route_ip_created_idx
  on public.request_rate_limits (route_key, client_ip, created_at desc);

create index if not exists request_rate_limits_created_idx
  on public.request_rate_limits (created_at desc);
