import type { ConsulateInfo, SpainConsulateId, SpainRegionCode } from '@/types'

export const spainRegionToConsulate: Record<SpainRegionCode, SpainConsulateId> = {
  'Comunidad de Madrid': 'madrid',
  'Islas Canarias': 'madrid',
  'Castilla y León - Ávila': 'madrid',
  'Castilla y León - León': 'madrid',
  'Castilla y León - Palencia': 'madrid',
  'Castilla y León - Salamanca': 'madrid',
  'Castilla y León - Segovia': 'madrid',
  'Castilla y León - Soria': 'madrid',
  'Castilla y León - Valladolid': 'madrid',
  'Castilla y León - Zamora': 'madrid',
  'Castilla y León - Burgos': 'bilbao',
  'Castilla-La Mancha - Guadalajara': 'madrid',
  'Castilla-La Mancha - Toledo': 'ciudadreal',
  'Castilla-La Mancha - Ciudad Real': 'ciudadreal',
  'Castilla-La Mancha - Albacete': 'ciudadreal',
  'Castilla-La Mancha - Cuenca': 'ciudadreal',
  'Cataluña': 'barcelona',
  'Islas Baleares': 'barcelona',
  'Comunidad Valenciana': 'valencia',
  'Andalucía - Huelva': 'sevilla',
  'Andalucía - Cádiz': 'sevilla',
  'Andalucía - Málaga': 'sevilla',
  'Andalucía - Sevilla': 'sevilla',
  'Andalucía - Córdoba': 'sevilla',
  'Extremadura': 'sevilla',
  Ceuta: 'sevilla',
  Melilla: 'sevilla',
  Galicia: 'bilbao',
  'Principado de Asturias': 'bilbao',
  Cantabria: 'bilbao',
  'País Vasco': 'bilbao',
  'Comunidad Foral de Navarra': 'bilbao',
  'La Rioja': 'bilbao',
  'Aragón': 'zaragoza',
  'Andalucía - Almería': 'almeria',
  'Andalucía - Granada': 'almeria',
  'Andalucía - Jaén': 'almeria',
  'Región de Murcia': 'almeria',
}

export const spainRegionOptions: { code: SpainRegionCode; name: string }[] = [
  { code: 'Comunidad de Madrid', name: 'Comunidad de Madrid' },
  { code: 'Islas Canarias', name: 'Islas Canarias' },
  { code: 'Castilla y León - Ávila', name: 'Castilla y León · Ávila' },
  { code: 'Castilla y León - León', name: 'Castilla y León · León' },
  { code: 'Castilla y León - Palencia', name: 'Castilla y León · Palencia' },
  { code: 'Castilla y León - Salamanca', name: 'Castilla y León · Salamanca' },
  { code: 'Castilla y León - Segovia', name: 'Castilla y León · Segovia' },
  { code: 'Castilla y León - Soria', name: 'Castilla y León · Soria' },
  { code: 'Castilla y León - Valladolid', name: 'Castilla y León · Valladolid' },
  { code: 'Castilla y León - Zamora', name: 'Castilla y León · Zamora' },
  { code: 'Castilla y León - Burgos', name: 'Castilla y León · Burgos' },
  { code: 'Castilla-La Mancha - Guadalajara', name: 'Castilla-La Mancha · Guadalajara' },
  { code: 'Castilla-La Mancha - Toledo', name: 'Castilla-La Mancha · Toledo' },
  { code: 'Castilla-La Mancha - Ciudad Real', name: 'Castilla-La Mancha · Ciudad Real' },
  { code: 'Castilla-La Mancha - Albacete', name: 'Castilla-La Mancha · Albacete' },
  { code: 'Castilla-La Mancha - Cuenca', name: 'Castilla-La Mancha · Cuenca' },
  { code: 'Cataluña', name: 'Cataluña' },
  { code: 'Islas Baleares', name: 'Islas Baleares' },
  { code: 'Comunidad Valenciana', name: 'Comunidad Valenciana' },
  { code: 'Andalucía - Huelva', name: 'Andalucía · Huelva' },
  { code: 'Andalucía - Cádiz', name: 'Andalucía · Cádiz' },
  { code: 'Andalucía - Málaga', name: 'Andalucía · Málaga' },
  { code: 'Andalucía - Sevilla', name: 'Andalucía · Sevilla' },
  { code: 'Andalucía - Córdoba', name: 'Andalucía · Córdoba' },
  { code: 'Extremadura', name: 'Extremadura' },
  { code: 'Ceuta', name: 'Ceuta' },
  { code: 'Melilla', name: 'Melilla' },
  { code: 'Galicia', name: 'Galicia' },
  { code: 'Principado de Asturias', name: 'Principado de Asturias' },
  { code: 'Cantabria', name: 'Cantabria' },
  { code: 'País Vasco', name: 'País Vasco' },
  { code: 'Comunidad Foral de Navarra', name: 'Comunidad Foral de Navarra' },
  { code: 'La Rioja', name: 'La Rioja' },
  { code: 'Aragón', name: 'Aragón' },
  { code: 'Andalucía - Almería', name: 'Andalucía · Almería' },
  { code: 'Andalucía - Granada', name: 'Andalucía · Granada' },
  { code: 'Andalucía - Jaén', name: 'Andalucía · Jaén' },
  { code: 'Región de Murcia', name: 'Región de Murcia' },
]

export const spainConsulates: Record<SpainConsulateId, ConsulateInfo> = {
  madrid: {
    countryCode: 'es',
    id: 'madrid',
    name: 'Consulatul General al României la Madrid',
    address: 'Avenida de Alfonso XIII 157, 28016 Madrid',
    phone: '+34 917.344.004',
    phoneNote: 'urgențe: +34 669.362.202',
    email: 'contact@informatiiconsulare.ro',
    website: 'https://madrid.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Avenida+Alfonso+XIII+157%2C+28016+Madrid',
    wazeUrl: 'https://waze.com/ul?ll=40.4583,-3.6897&navigate=yes',
    scheduleDeponere: 'Luni–Joi 08:00–15:00 · Vineri 08:00–13:00 · cu programare pe econsulat.ro',
    scheduleRidicare: 'Luni–Miercuri 08:00–15:00 (fără programare) · Joi și Vineri nu se ridică pașapoarte',
    schedulePassportPickup: 'Luni–Miercuri 08:00–15:00 (fără programare) · Joi și Vineri nu se ridică pașapoarte',
    schedulePassportPickupCrds: 'Pașaportul CRDS se trimite poștal obligatoriu · 7€ taxa poștală inclusă',
    schedulePassportPickupStandard: 'Luni–Miercuri 08:00–15:00 (fără programare)',
    scheduleTitluCalatorie: 'Luni–Vineri în programul consulatului · verifică direct urgențele',
    scheduleTravelDoc: 'Luni–Vineri în programul consulatului · verifică direct urgențele',
    paymentMethod: 'exclusiv card bancar',
    paymentPassport: '53€ · exclusiv card bancar',
    paymentPassportCrds: '60€ · exclusiv card bancar',
    paymentPassportNote: 'Taxa legală reală este 53€. Pentru CRDS la Madrid se adaugă 7€ taxă poștală obligatorie, total 60€.',
    paymentPassportCrdsNote: 'Taxa totală pentru pașaportul CRDS la Madrid este 60€: 53€ taxa legală + 7€ taxa poștală obligatorie.',
    paymentNotarial: 'gratuit · RNNEPR nu se aplică în Spania',
    paymentNotarialNote: 'Procura consulară este gratuită în Spania.',
    postalPickup: true,
    postalPickupUrl: 'https://madrid.mae.ro',
    pasaportSearchUrl: 'https://madrid.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
  },
  barcelona: {
    countryCode: 'es',
    id: 'barcelona',
    name: 'Consulatul General al României la Barcelona',
    address: 'Carrer de Munner 10, 08022 Barcelona',
    addressNote: 'Adresă nouă din 02.06.2025 — nu folosi adresa veche.',
    phone: '+34 933.181.783',
    phoneNote: 'verifică direct și linia de urgență de pe site',
    email: 'contact@informatiiconsulare.ro',
    website: 'https://barcelona.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Carrer+de+Munner+10%2C+08022+Barcelona',
    wazeUrl: 'https://waze.com/ul?ll=41.4065,2.1408&navigate=yes',
    scheduleDeponere: 'Luni–Vineri 09:00–15:00 · cu programare pe econsulat.ro',
    scheduleRidicare: 'Luni–Vineri 15:30–17:00 (fără programare)',
    schedulePassportPickup: 'Luni–Vineri 15:30–17:00 (fără programare)',
    scheduleTitluCalatorie: 'Conform programului consulatului · verifică direct regula exactă',
    scheduleTravelDoc: 'Conform programului consulatului · verifică direct regula exactă',
    paymentMethod: '⚠️ metoda de plată nu este specificată clar pe site',
    paymentPassport: '53€ · metoda de plată trebuie confirmată direct',
    paymentPassportNote: 'Taxa legală reală este 53€, deși unele pagini MAE afișează încă 59€.',
    paymentNotarial: 'gratuit · RNNEPR nu se aplică în Spania',
    paymentNotarialNote: 'Procura consulară este gratuită în Spania.',
    postalPickup: false,
    pasaportSearchUrl: 'https://barcelona.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
  },
  valencia: {
    countryCode: 'es',
    id: 'valencia',
    name: 'Consulatul General al României la Valencia',
    address: 'Plaza de Alfonso el Magnánimo 12, 46003 Valencia',
    phone: '+34 677.842.467',
    phoneNote: 'același număr este folosit și pentru urgențe',
    email: 'contact@informatiiconsulare.ro',
    website: 'https://valencia.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Plaza+Alfonso+el+Magnanimo+12%2C+46003+Valencia',
    wazeUrl: 'https://waze.com/ul?ll=39.4738,-0.3747&navigate=yes',
    scheduleDeponere: 'Luni–Vineri 09:00–15:00 · cu programare pe econsulat.ro',
    scheduleRidicare: 'Luni–Joi 15:30–17:00 (fără programare)',
    schedulePassportPickup: 'Luni–Joi 15:30–17:00 (fără programare)',
    scheduleTitluCalatorie: 'Luni–Vineri 09:00–15:00 · cu programare pe econsulat.ro',
    scheduleTravelDoc: 'Luni–Vineri în programul consulatului · verifică direct urgențele',
    paymentMethod: '⚠️ metoda de plată nu este specificată clar pe site',
    paymentPassport: '53€ · metoda de plată trebuie confirmată direct',
    paymentPassportNote: 'Taxa legală reală este 53€. Unele pagini MAE pot afișa încă 59€.',
    paymentNotarial: 'gratuit · RNNEPR nu se aplică în Spania',
    paymentNotarialNote: 'Procura consulară este gratuită în Spania.',
    postalPickup: true,
    postalPickupUrl: 'https://valencia.mae.ro/node/1441',
    pasaportSearchUrl: 'https://valencia.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
  },
  sevilla: {
    countryCode: 'es',
    id: 'sevilla',
    name: 'Consulatul General al României la Sevilla',
    address: 'Avenida Manuel Siurot 30, 41013 Sevilla',
    phone: '+34 648.212.169',
    phoneNote: 'același număr este folosit și pentru urgențe',
    email: 'contact@informatiiconsulare.ro',
    website: 'https://sevilla.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Avenida+Manuel+Siurot+30%2C+41013+Sevilla',
    wazeUrl: 'https://waze.com/ul?ll=37.3742,-5.9825&navigate=yes',
    scheduleDeponere: 'Luni–Joi 09:00–14:30 · Vineri 09:00–13:00 · cu programare pe econsulat.ro',
    scheduleRidicare: 'Luni–Joi 14:00–15:00 · Vineri 13:00–14:00 (fără programare)',
    schedulePassportPickup: 'Luni–Joi 14:00–15:00 · Vineri 13:00–14:00 (fără programare)',
    scheduleTitluCalatorie: 'Cu programare pe econsulat.ro · verifică pe linia de urgență cazurile speciale',
    scheduleTravelDoc: 'Cu programare pe econsulat.ro · verifică direct urgențele',
    paymentMethod: '⚠️ metoda de plată nu este specificată clar pe site',
    paymentPassport: '53€ · metoda de plată trebuie confirmată direct',
    paymentPassportNote: 'Taxa legală reală este 53€. Verifică direct metoda de plată.',
    paymentNotarial: 'gratuit · RNNEPR nu se aplică în Spania',
    paymentNotarialNote: 'Procura consulară este gratuită în Spania.',
    postalPickup: true,
    postalPickupUrl: 'https://sevilla.mae.ro',
    pasaportSearchUrl: 'https://sevilla.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
  },
  bilbao: {
    countryCode: 'es',
    id: 'bilbao',
    name: 'Consulatul General al României la Bilbao',
    address: 'Plaza Circular 4, 48001 Bilbao',
    phone: '+34 608.956.278',
    phoneNote: 'același număr este folosit și pentru urgențe',
    email: 'contact@informatiiconsulare.ro',
    website: 'https://bilbao.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Plaza+Circular+4%2C+48001+Bilbao',
    wazeUrl: 'https://waze.com/ul?ll=43.2617,-2.9344&navigate=yes',
    scheduleDeponere: 'Luni–Joi 08:30–13:30 · cu programare · Vineri exclusiv servicii speciale, nu pașapoarte obișnuite',
    scheduleRidicare: 'Luni–Joi 08:30–13:30 (în același interval cu depunerea)',
    schedulePassportPickup: 'Luni–Joi 08:30–13:30 (în același interval cu depunerea)',
    scheduleTitluCalatorie: 'Cu programare pe econsulat.ro · verifică direct excepțiile',
    scheduleTravelDoc: 'Cu programare pe econsulat.ro · verifică direct excepțiile',
    paymentMethod: '⚠️ metoda de plată nu este specificată clar pe site',
    paymentPassport: '53€ · metoda de plată trebuie confirmată direct',
    paymentPassportNote: 'Vinerea nu se foloseste pentru pașapoarte obișnuite. Verifică direct și metoda de plată.',
    paymentNotarial: 'gratuit · RNNEPR nu se aplică în Spania',
    paymentNotarialNote: 'Procura consulară este gratuită în Spania.',
    postalPickup: false,
    pasaportSearchUrl: 'https://bilbao.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
  },
  zaragoza: {
    countryCode: 'es',
    id: 'zaragoza',
    name: 'Consulatul României la Zaragoza',
    address: 'Calle Camino de Las Torres 24, 50008 Zaragoza',
    addressNote: 'Intrarea pentru public este prin spatele clădirii.',
    phone: '+34 976.481.429',
    phoneNote: 'urgențe: +34 663.814.474',
    email: 'contact@informatiiconsulare.ro',
    website: 'https://zaragoza.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Calle+Camino+de+Las+Torres+24%2C+50008+Zaragoza',
    wazeUrl: 'https://waze.com/ul?ll=41.6524,-0.8980&navigate=yes',
    scheduleDeponere: 'Luni–Vineri 09:00–14:00 · cu programare pe econsulat.ro',
    scheduleRidicare: 'Luni–Vineri 14:00–15:00 (fără programare)',
    schedulePassportPickup: 'Luni–Vineri 14:00–15:00 (fără programare)',
    scheduleTitluCalatorie: 'Fără programare în urgențe, cu documente justificative',
    scheduleTravelDoc: 'Fără programare în urgențe, cu documente justificative',
    paymentMethod: 'numerar sau POS',
    paymentPassport: '53€ · numerar sau POS la ghișeu',
    paymentPassportNote: 'Taxa de 53€ este confirmată explicit pe pagina consulatului.',
    paymentNotarial: 'gratuit · numerar sau POS dacă există alte costuri auxiliare',
    paymentNotarialNote: 'Procura consulară este gratuită în Spania.',
    postalPickup: false,
    pasaportSearchUrl: 'https://zaragoza.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
  },
  ciudadreal: {
    countryCode: 'es',
    id: 'ciudadreal',
    name: 'Consulatul României la Ciudad Real',
    address: 'Calle Mata 37, 13004 Ciudad Real',
    phone: '+34 609.513.790',
    phoneNote: 'același număr este folosit și pentru urgențe',
    email: 'contact@informatiiconsulare.ro',
    website: 'https://ciudadreal.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Calle+Mata+37%2C+13004+Ciudad+Real',
    wazeUrl: 'https://waze.com/ul?ll=38.9848,-3.9301&navigate=yes',
    scheduleDeponere: 'Luni–Joi 09:00–14:00 · Vineri 09:00–12:00 · cu programare pe econsulat.ro',
    scheduleRidicare: 'Luni–Joi 15:00–16:00 (fără programare)',
    schedulePassportPickup: 'Luni–Joi 15:00–16:00 (fără programare)',
    scheduleTitluCalatorie: 'Cu programare pe econsulat.ro',
    scheduleTravelDoc: 'Cu programare pe econsulat.ro',
    paymentMethod: 'exclusiv numerar',
    paymentPassport: '53€ · exclusiv numerar',
    paymentPassportNote: 'Taxa reală este 53€. Vineri 12:00–14:00 este rezervat căsătoriilor, nu altor servicii.',
    paymentNotarial: 'gratuit · RNNEPR nu se aplică în Spania',
    paymentNotarialNote: 'Procura consulară este gratuită în Spania.',
    postalPickup: false,
    pasaportSearchUrl: 'https://ciudadreal.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
  },
  almeria: {
    countryCode: 'es',
    id: 'almeria',
    name: 'Consulatul României la Almería',
    address: 'Carretera Huércal de Almería 46, 04009 Almería',
    phone: '+34 950.625.963',
    phoneNote: 'urgențe: +34 682.733.408',
    email: 'contact@informatiiconsulare.ro',
    website: 'https://almeria.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Carretera+Huercal+de+Almeria+46%2C+04009+Almeria',
    wazeUrl: 'https://waze.com/ul?ll=36.8719,-2.4098&navigate=yes',
    scheduleDeponere: 'Luni–Joi 09:00–14:00 · Vineri 09:00–12:00 · cu programare pe econsulat.ro',
    scheduleRidicare: 'Luni–Joi 16:00–17:00 · Vineri 12:00–13:00 (fără programare)',
    schedulePassportPickup: 'Luni–Joi 16:00–17:00 · Vineri 12:00–13:00 (fără programare)',
    scheduleTitluCalatorie: 'Cu programare pe econsulat.ro',
    scheduleTravelDoc: 'Cu programare pe econsulat.ro',
    paymentMethod: '⚠️ metoda de plată nu este specificată clar pe site',
    paymentPassport: '53€ · metoda de plată trebuie confirmată direct',
    paymentPassportNote: 'Taxa reală este 53€. Verifică direct metoda de plată înainte de drum.',
    paymentNotarial: 'gratuit · RNNEPR nu se aplică în Spania',
    paymentNotarialNote: 'Procura consulară este gratuită în Spania.',
    postalPickup: false,
    pasaportSearchUrl: 'https://almeria.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
  },
}
