import type { ConsulateInfo, ItalyConsulateId, ItalyRegionCode } from '@/types'

export const italyRegionToConsulate: Record<ItalyRegionCode, ItalyConsulateId> = {
  Lazio: 'roma',
  Abruzzo: 'roma',
  Campania: 'roma',
  Molise: 'bari',
  Sardegna: 'roma',
  Umbria: 'roma',
  Lombardia: 'milano',
  'Trentino-Alto Adige': 'milano',
  'Emilia-Romagna': 'bologna',
  Marche: 'bologna',
  Toscana: 'bologna',
  'San Marino': 'bologna',
  Piemonte: 'torino',
  Liguria: 'torino',
  "Valle d'Aosta": 'torino',
  Veneto: 'trieste',
  'Friuli-Venezia Giulia': 'trieste',
  Basilicata: 'bari',
  Calabria: 'bari',
  Puglia: 'bari',
  Sicilia: 'catania',
}

export const italyRegionOptions: { code: ItalyRegionCode; name: string }[] = [
  { code: 'Lazio', name: 'Lazio' },
  { code: 'Abruzzo', name: 'Abruzzo' },
  { code: 'Campania', name: 'Campania' },
  { code: 'Molise', name: 'Molise' },
  { code: 'Sardegna', name: 'Sardegna' },
  { code: 'Umbria', name: 'Umbria' },
  { code: 'Lombardia', name: 'Lombardia' },
  { code: 'Trentino-Alto Adige', name: 'Trentino-Alto Adige' },
  { code: 'Emilia-Romagna', name: 'Emilia-Romagna' },
  { code: 'Marche', name: 'Marche' },
  { code: 'Toscana', name: 'Toscana' },
  { code: 'San Marino', name: 'San Marino' },
  { code: 'Piemonte', name: 'Piemonte' },
  { code: 'Liguria', name: 'Liguria' },
  { code: "Valle d'Aosta", name: "Valle d'Aosta" },
  { code: 'Veneto', name: 'Veneto' },
  { code: 'Friuli-Venezia Giulia', name: 'Friuli-Venezia Giulia' },
  { code: 'Basilicata', name: 'Basilicata' },
  { code: 'Calabria', name: 'Calabria' },
  { code: 'Puglia', name: 'Puglia' },
  { code: 'Sicilia', name: 'Sicilia' },
]

export const italyConsulates: Record<ItalyConsulateId, ConsulateInfo> = {
  roma: {
    countryCode: 'it',
    id: 'roma',
    name: 'Consulatul General al României la Roma',
    address: 'Viale Libano 40, 00144 Roma',
    phone: '+39 345.147.3935',
    phoneNote: 'urgențe consulare și clarificări rapide',
    email: 'cgroma@mae.ro',
    website: 'https://cgroma.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Viale+Libano+40%2C+00144+Roma',
    wazeUrl: 'https://waze.com/ul?ll=41.8553,12.4724&navigate=yes',
    scheduleDeponere: 'Luni–Joi 09:00–15:00 · cu programare pe econsulat.ro · Vineri fără pașapoarte obișnuite',
    scheduleRidicare: 'Luni–Joi 09:00–14:00 (fără programare · non-CRDS)',
    schedulePassportPickup: 'Luni–Vineri 14:30–16:00 (fără programare · CRDS)',
    schedulePassportPickupCrds: 'Luni–Vineri 14:30–16:00 (fără programare · CRDS)',
    schedulePassportPickupStandard: 'Luni–Joi 09:00–14:00 (fără programare · non-CRDS)',
    scheduleTitluCalatorie: 'Luni–Vineri 11:00–13:00 (urgențe fără programare · max 2 săptămâni)',
    scheduleTravelDoc: 'Luni–Vineri 11:00–13:00 pentru urgențe fără programare · altfel cu programare pe econsulat.ro',
    paymentMethod: 'metoda de plată nu este specificată explicit pe site',
    paymentPassport: 'pagina afișează 59€; taxa reală este probabil 53€ — confirmă direct la consulat',
    paymentNotarial: 'virament bancar în avans pentru taxa RNNEPR (3€ +, după caz, verificarea registrului)',
    paymentNote: 'Metoda de plată pentru pașaport nu este specificată explicit pe site-ul oficial.',
    paymentNotarialNote: 'IBAN-ul pentru plata notarială se ia din econsulat.ro sau direct de la ghișeu.',
    postalPickup: true,
    paymentPassportNote: 'Site-ul afișează încă 59€; confirmă direct suma finală înainte de depunere.',
    postalPickupUrl: 'https://cgroma.mae.ro',
    pasaportSearchUrl: 'https://cgroma.mae.ro/cauta-pasaport',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'Luni–Joi 09:00–14:00',
    starecivilaPosta: false,
    starecivilaTermen: 'termen nepublicat oficial',
  },
  milano: {
    countryCode: 'it',
    id: 'milano',
    name: 'Consulatul General al României la Milano',
    address: 'Via Gignese 2, 20148 Milano',
    phone: '+39 366.108.1444',
    phoneNote: 'urgențe consulare și titluri urgente',
    email: 'milano@mae.ro',
    website: 'https://milano.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Via+Gignese+2%2C+20148+Milano',
    wazeUrl: 'https://waze.com/ul?ll=45.4537,9.1355&navigate=yes',
    scheduleDeponere: 'Luni–Vineri 09:00–12:30 și 13:30–16:00 · cu programare',
    scheduleRidicare: 'Luni–Vineri 09:00–10:00 și 14:00–15:00 (fără programare)',
    schedulePassportPickup: 'Luni–Vineri 09:00–10:00 și 14:00–15:00 (fără programare)',
    schedulePassportPickupCrds: 'Luni–Vineri 09:00–10:00 și 14:00–15:00 (fără programare)',
    schedulePassportPickupStandard: 'Luni–Vineri 09:00–10:00 și 14:00–15:00 (fără programare)',
    scheduleTitluCalatorie: 'titlurile urgente se rezolvă fără programare după apel pe linia de urgență',
    scheduleTravelDoc: 'titlu urgent fără programare după apel pe linia de urgență · non-urgent cu programare',
    paymentMethod: 'numerar sau card bancar',
    paymentPassport: 'numerar sau card bancar la ghișeu',
    paymentNotarial: 'virament bancar în avans pentru taxa RNNEPR',
    paymentPassportNote: 'Pagina afișează 59€, dar taxa legală poate fi 53€; confirmă înainte de drum.',
    paymentNotarialNote: 'IBAN-ul pentru notarial se primește prin econsulat.ro sau direct la ghișeu.',
    postalPickup: true,
    postalPickupUrl: 'https://milano.mae.ro',
    pasaportSearchUrl: 'https://milano.mae.ro/cauta-pasaport',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'Luni–Vineri 09:00–10:00 și 14:00–15:00',
    starecivilaPosta: false,
    starecivilaTermen: 'aceeași zi pentru cazuri simple',
    munchenAcelasiZiBonusPasaport: true,
  },
  bologna: {
    countryCode: 'it',
    id: 'bologna',
    name: 'Consulatul General al României la Bologna',
    address: 'Via Guelfa 9, Scala A, Int. 3, 40138 Bologna',
    phone: '+39 349.117.8220',
    phoneNote: 'urgențe consulare și clarificări rapide',
    email: 'bologna@mae.ro',
    website: 'https://bologna.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Via+Guelfa+9%2C+40138+Bologna',
    wazeUrl: 'https://waze.com/ul?ll=44.4965,11.3378&navigate=yes',
    scheduleDeponere: 'Luni–Vineri 09:00–14:00 · fără programare obligatorie pentru fluxurile uzuale',
    scheduleRidicare: 'Luni–Joi 15:00–17:00 (fără programare)',
    schedulePassportPickup: 'Luni–Joi 15:00–17:00 (fără programare)',
    schedulePassportPickupCrds: 'Luni–Joi 15:00–17:00 (fără programare)',
    schedulePassportPickupStandard: 'Luni–Joi 15:00–17:00 (fără programare)',
    scheduleTitluCalatorie: 'walk-in cu documente justificative · biletul de avion singur nu este suficient ca urgență',
    scheduleTravelDoc: 'walk-in cu documente justificative · pentru fluxul uzual nu este obligatorie programarea',
    paymentMethod: 'metoda de plată nu este specificată clar pe site',
    paymentPassport: 'pagina afișează 59€; taxa reală este probabil 53€ — confirmă direct la ghișeu',
    paymentNotarial: 'virament bancar în avans pentru taxa RNNEPR',
    paymentPassportNote: 'Bologna afișează încă 59€ pe site; confirmă direct suma finală și metoda de plată.',
    paymentNotarialNote: 'IBAN-ul pentru notarial se primește prin econsulat.ro sau direct la ghișeu.',
    postalPickup: true,
    postalPickupUrl: 'https://bologna.mae.ro/node/1250',
    pasaportSearchUrl: 'https://bologna.mae.ro/cauta-pasaport',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'Luni–Joi 15:00–17:00',
    starecivilaPosta: false,
    starecivilaTermen: 'termen nepublicat oficial',
  },
  torino: {
    countryCode: 'it',
    id: 'torino',
    name: 'Consulatul General al României la Torino',
    address: 'Via Ancona 7, 10152 Torino',
    phone: '+39 338.756.8134',
    phoneNote: 'urgențe și programări speciale',
    email: 'torino@mae.ro',
    website: 'https://torino.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Via+Ancona+7%2C+10152+Torino',
    wazeUrl: 'https://waze.com/ul?ll=45.0648,7.6896&navigate=yes',
    scheduleDeponere: 'toate serviciile exclusiv cu programare pe econsulat.ro',
    scheduleRidicare: 'Joi 14:30–15:30 (fără programare) sau prin plic preplătit autoadresat',
    schedulePassportPickup: 'Joi 14:30–15:30 (fără programare) sau prin plic preplătit autoadresat',
    schedulePassportPickupCrds: 'Joi 14:30–15:30 (fără programare) sau prin plic preplătit autoadresat',
    schedulePassportPickupStandard: 'Joi 14:30–15:30 (fără programare) sau prin plic preplătit autoadresat',
    scheduleTitluCalatorie: 'exclusiv cu programare pe econsulat.ro · nu există walk-in nici pentru urgențe',
    scheduleTravelDoc: 'exclusiv cu programare pe econsulat.ro · fără walk-in',
    paymentMethod: 'numerar la ghișeu',
    paymentPassport: '53€ numerar la ghișeu',
    paymentNotarial: 'virament bancar în avans pentru taxa RNNEPR',
    paymentNotarialNote: 'IBAN-ul pentru notarial se primește din econsulat.ro sau direct de la consulat.',
    postalPickup: true,
    paymentPassportNote: 'Taxa de 53€ este confirmată explicit de consulat.',
    postalPickupUrl: 'https://torino.mae.ro',
    pasaportSearchUrl: 'https://torino.mae.ro/cauta-pasaport',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'Joi 14:30–15:30',
    starecivilaPosta: true,
    starecivilaTermen: 'termen nepublicat oficial',
  },
  trieste: {
    countryCode: 'it',
    id: 'trieste',
    name: 'Consulatul General al României la Trieste',
    address: 'Via Udine 11, 34132 Trieste',
    phone: '+39 340.882.1688',
    phoneNote: 'urgențe consulare și clarificări rapide',
    email: 'trieste@mae.ro',
    website: 'https://trieste.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Via+Udine+11%2C+34132+Trieste',
    wazeUrl: 'https://waze.com/ul?ll=45.6534,13.7776&navigate=yes',
    scheduleDeponere: 'Luni–Joi și Vineri 09:00–14:00 · toate serviciile exclusiv cu programare',
    scheduleRidicare: 'Luni–Joi 15:30–16:30 · Vineri 14:00–15:00 (fără programare)',
    schedulePassportPickup: 'Luni–Joi 15:30–16:30 · Vineri 14:00–15:00 (fără programare)',
    schedulePassportPickupCrds: 'Luni–Joi 15:30–16:30 · Vineri 14:00–15:00 (fără programare)',
    schedulePassportPickupStandard: 'Luni–Joi 15:30–16:30 · Vineri 14:00–15:00 (fără programare)',
    scheduleTitluCalatorie: 'cu programare pe econsulat.ro · fără interval walk-in confirmat',
    scheduleTravelDoc: 'cu programare pe econsulat.ro · fără interval walk-in confirmat',
    paymentMethod: 'numerar la ghișeu',
    paymentPassport: '53€ numerar la ghișeu',
    paymentNotarial: 'virament bancar în avans pentru 3€ RNNEPR + 5€ verificare registru',
    paymentPassportNote: 'Taxa de 53€ este confirmată explicit de consulat.',
    paymentNotarialNote: 'Trieste cere 3€ RNNEPR plus 5€ verificare registru, plătite în avans.',
    postalPickup: true,
    postalPickupUrl: 'https://trieste.mae.ro',
    pasaportSearchUrl: 'https://trieste.mae.ro/cauta-pasaport',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'Luni–Joi 15:30–16:30 · Vineri 14:00–15:00',
    starecivilaPosta: false,
    starecivilaTermen: '~20 zile',
  },
  bari: {
    countryCode: 'it',
    id: 'bari',
    name: 'Consulatul General al României la Bari',
    address: 'Via Bruno Zaccaro 19, 70126 Bari',
    phone: '+39 334.604.2299',
    phoneNote: 'urgențe consulare și programări',
    email: 'bari@mae.ro',
    website: 'https://bari.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Via+Bruno+Zaccaro+19%2C+70126+Bari',
    wazeUrl: 'https://waze.com/ul?ll=41.1216,16.8699&navigate=yes',
    scheduleDeponere: 'Luni–Vineri 09:00–15:00 · cu programare pe econsulat.ro sau bari.programari@mae.ro',
    scheduleRidicare: 'Luni–Joi 09:00–15:00 (fără interval separat dedicat)',
    schedulePassportPickup: 'Luni–Joi 09:00–15:00 (fără interval separat dedicat)',
    schedulePassportPickupCrds: 'Luni–Joi 09:00–15:00 (fără interval separat dedicat)',
    schedulePassportPickupStandard: 'Luni–Joi 09:00–15:00 (fără interval separat dedicat)',
    scheduleTitluCalatorie: 'probabil cu programare pe econsulat.ro · fără walk-in confirmat',
    scheduleTravelDoc: 'probabil cu programare pe econsulat.ro · fără walk-in confirmat',
    paymentMethod: 'numerar la ghișeu',
    paymentPassport: '53€ numerar la ghișeu',
    paymentNotarial: 'virament bancar în avans pentru taxa RNNEPR',
    paymentPassportNote: 'Taxa de 53€ este confirmată explicit de consulat.',
    paymentNotarialNote: 'IBAN-ul pentru notarial se primește prin econsulat.ro sau direct la ghișeu.',
    postalPickup: true,
    postalPickupUrl: 'https://bari.mae.ro',
    pasaportSearchUrl: 'https://bari.mae.ro/cauta-pasaport',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'Luni–Vineri 09:00–15:00',
    starecivilaPosta: true,
    starecivilaTermen: '~20 zile · de confirmat direct',
  },
  catania: {
    countryCode: 'it',
    id: 'catania',
    name: 'Consulatul României la Catania',
    address: 'Via Misterbianco 1, 95131 Catania',
    phone: '+39 320.965.3137',
    phoneNote: 'confirmare directă obligatorie înainte de orice deplasare',
    email: 'catania@mae.ro',
    website: 'https://catania.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Via+Misterbianco+1%2C+95131+Catania',
    wazeUrl: 'https://waze.com/ul?ll=37.5102,15.0845&navigate=yes',
    scheduleDeponere: 'Luni–Joi 09:00–15:00 · cu programare pe econsulat.ro',
    scheduleRidicare: 'Luni–Joi 09:00–15:00 (program general · interval dedicat neconfirmat)',
    schedulePassportPickup: 'Luni–Joi 09:00–15:00 (program general · interval dedicat neconfirmat)',
    schedulePassportPickupCrds: 'Luni–Joi 09:00–15:00 (de confirmat direct)',
    schedulePassportPickupStandard: 'Luni–Joi 09:00–15:00 (de confirmat direct)',
    scheduleTitluCalatorie: 'cu programare · fără urgențe walk-in confirmate',
    scheduleTravelDoc: 'cu programare · confirmare directă obligatorie înainte de deplasare',
    paymentMethod: 'confirmare directă obligatorie',
    paymentPassport: 'taxa reală estimată 53€ · site-ul afișează greșit 100€',
    paymentNotarial: 'virament bancar în avans pentru taxa RNNEPR',
    paymentPassportNote: 'Site-ul este neîntreținut și afișează sume greșite; confirmă direct la consulat.',
    paymentNotarialNote: 'Pentru notarial, ia detaliile de plată direct din econsulat.ro sau de la consulat.',
    postalPickup: false,
    pasaportSearchUrl: 'https://catania.mae.ro/cauta-pasaport',
    staffShortageNotice: true,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'Luni–Joi 09:00–15:00 (de confirmat direct)',
    starecivilaPosta: false,
    starecivilaTermen: 'nepublicat oficial',
  },
}

export function getItalyConsulateByRegion(region: ItalyRegionCode): ConsulateInfo {
  return italyConsulates[italyRegionToConsulate[region]]
}

export function getItalyConsulateById(id: ItalyConsulateId): ConsulateInfo {
  return italyConsulates[id]
}
