import type { ConsulateInfo, UkConsulateId, UkRegionCode } from '@/types'

export const ukRegionToConsulate: Record<UkRegionCode, UkConsulateId> = {
  'Londra (Greater London)': 'londra',
  'Sud-Est Anglia (South East England)': 'londra',
  'Sud-Vest Anglia (South West England)': 'londra',
  'East of England': 'londra',
  'East Midlands': 'londra',
  'West Midlands': 'londra',
  'Țara Galilor (Wales)': 'londra',
  'Greater Manchester': 'manchester',
  'Nord-Vest Anglia (North West England)': 'manchester',
  'Nord-Est Anglia și Yorkshire': 'manchester',
  'Scoția (Scotland)': 'edinburgh',
  'Irlanda de Nord (Northern Ireland)': 'edinburgh',
}

export const ukRegionOptions: { code: UkRegionCode; name: string }[] = [
  { code: 'Londra (Greater London)', name: 'Londra (Greater London)' },
  { code: 'Sud-Est Anglia (South East England)', name: 'Sud-Est Anglia (South East England)' },
  { code: 'Sud-Vest Anglia (South West England)', name: 'Sud-Vest Anglia (South West England)' },
  { code: 'East of England', name: 'East of England' },
  { code: 'East Midlands', name: 'East Midlands' },
  { code: 'West Midlands', name: 'West Midlands' },
  { code: 'Țara Galilor (Wales)', name: 'Țara Galilor (Wales)' },
  { code: 'Greater Manchester', name: 'Greater Manchester' },
  { code: 'Nord-Vest Anglia (North West England)', name: 'Nord-Vest Anglia (North West England)' },
  { code: 'Nord-Est Anglia și Yorkshire', name: 'Nord-Est Anglia și Yorkshire' },
  { code: 'Scoția (Scotland)', name: 'Scoția (Scotland)' },
  { code: 'Irlanda de Nord (Northern Ireland)', name: 'Irlanda de Nord (Northern Ireland)' },
]

export const ukConsulates: Record<UkConsulateId, ConsulateInfo> = {
  londra: {
    countryCode: 'uk',
    id: 'londra',
    name: 'Consulatul General al României la Londra',
    address: 'Glen House, etajul 1, 22 Glenthorne Road, Hammersmith, London W6 0PP',
    phone: '+44 20 8741 3252',
    phoneNote: 'urgențe: +44 77 387 16 335 · pentru programare fără internet: 0742 528 5318',
    email: 'contact@informatiiconsulare.ro',
    website: 'https://cglondra.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22+Glenthorne+Road%2C+Hammersmith%2C+London+W6+0PP',
    wazeUrl: 'https://waze.com/ul?ll=51.4922,-0.2280&navigate=yes',
    scheduleDeponere: 'Luni–Joi 09:00–16:00 · Vineri 09:00–14:00 · cu programare pe econsulat.ro',
    scheduleRidicare: 'În programul general al consulatului · verifică statusul înainte de drum',
    schedulePassportPickup: 'În programul general al consulatului · verifică statusul înainte de drum',
    schedulePassportPickupCrds: 'Prin poștă (Royal Mail Special Delivery) dacă ai cerut plic preplătit la depunere',
    schedulePassportPickupStandard: 'În programul general al consulatului · verifică statusul înainte de drum',
    scheduleTitluCalatorie: 'Fără programare dacă dovedești plecare în max 7 zile lucrătoare',
    scheduleTravelDoc: 'Fără programare dacă dovedești plecare în max 7 zile lucrătoare',
    paymentMethod: 'preferabil card bancar (numerar acceptat)',
    paymentPassport: '~46 GBP · card sau numerar · taxa variază lunar',
    paymentPassportCrds: '~46 GBP · card sau numerar · taxa variază lunar',
    paymentPassportTemporary: '~46 GBP · card sau numerar · taxa variază lunar',
    paymentNotarial: '0 GBP fără incidență / 3 GBP cu incidență notarială',
    paymentPassportNote: 'Taxa de pașaport în UK este în GBP și se actualizează lunar. Verifică suma exactă pe site-ul consulatului.',
    paymentPassportCrdsNote: 'Taxa de pașaport CRDS în UK este în GBP și se actualizează lunar. Verifică suma exactă pe site-ul consulatului.',
    paymentPassportTemporaryNote: 'Taxa pentru pașaport temporar se actualizează lunar. Verifică suma exactă pe site-ul consulatului înainte de programare.',
    paymentNotarialNote: 'Procura cu incidență notarială poate implica 3 GBP.',
    postalPickup: true,
    postalPickupUrl: 'https://cglondra.mae.ro',
    pasaportSearchUrl: 'https://cglondra.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'În programul general · verifică direct la consulat',
    starecivilaPosta: true,
    starecivilaTermen: 'în aceeași zi pentru minori sub 14 ani, dacă dosarul este complet',
  },
  manchester: {
    countryCode: 'uk',
    id: 'manchester',
    name: 'Consulatul General al României la Manchester',
    address: '9 Cooper Street, Manchester, M2 2FW',
    addressNote: 'Adresă poștală separată: Abbey House, First Floor, 32 Booth Street, Manchester, M2 4AB',
    phone: '+44 161 236 0478',
    phoneNote: 'urgențe: +44 7535 604342 · programare fără internet: 07376 489 269',
    email: 'manchester.consul@mae.ro',
    website: 'https://manchester.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=9+Cooper+Street%2C+Manchester+M2+2FW',
    wazeUrl: 'https://waze.com/ul?ll=53.4794,-2.2424&navigate=yes',
    scheduleDeponere: 'Luni–Joi 09:00–14:00 și 15:00–16:30 · Vineri 09:00–14:00 · cu programare',
    scheduleRidicare: 'Luni–Joi 15:00–16:30 · Vineri 10:00–14:00',
    schedulePassportPickup: 'Luni–Joi 15:00–16:30 · Vineri 10:00–14:00',
    schedulePassportPickupCrds: 'Poștă Royal Mail Special Delivery dacă depui plic preplătit autoadresat',
    schedulePassportPickupStandard: 'Luni–Joi 15:00–16:30 · Vineri 10:00–14:00',
    scheduleTitluCalatorie: 'Programare obligatorie · urgențe în 48h doar prin email la manchester.consul@mae.ro',
    scheduleTravelDoc: 'Programare obligatorie · urgențe în 48h doar prin email',
    paymentMethod: 'exclusiv numerar (cash only)',
    paymentPassport: '~46 GBP · exclusiv numerar · taxa variază lunar',
    paymentPassportCrds: '~46 GBP · exclusiv numerar · taxa variază lunar',
    paymentPassportTemporary: '~46 GBP · exclusiv numerar · taxa variază lunar',
    paymentNotarial: '0 GBP fără incidență / 3 GBP cu incidență · exclusiv numerar',
    paymentPassportNote: 'Manchester acceptă EXCLUSIV numerar pentru pașaport. Verifică suma exactă pe site, fiind variabilă lunar.',
    paymentPassportCrdsNote: 'Manchester acceptă EXCLUSIV numerar pentru pașaportul CRDS. Verifică suma exactă pe site, fiind variabilă lunar.',
    paymentPassportTemporaryNote: 'Manchester acceptă EXCLUSIV numerar pentru pașaport temporar. Cererile se depun Luni–Joi 09:30–13:30.',
    paymentNotarialNote: 'Pentru serviciile notariale, Manchester acceptă numerar.',
    postalPickup: true,
    postalPickupUrl: 'https://manchester.mae.ro',
    pasaportSearchUrl: 'https://manchester.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'Verifică direct la consulat',
    starecivilaPosta: false,
    starecivilaTermen: 'în aceeași zi pentru minori sub 14 ani, dacă dosarul este complet',
  },
  edinburgh: {
    countryCode: 'uk',
    id: 'edinburgh',
    name: 'Consulatul General al României la Edinburgh',
    address: '7-9 North St. David Street, Edinburgh, EH2 1AW',
    phone: '+44 131 524 9498',
    phoneNote: 'urgențe: folosește emailul local edinburgh@mae.ro',
    email: 'edinburgh@mae.ro',
    website: 'https://edinburgh.mae.ro',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=7-9+North+St.+David+Street%2C+Edinburgh+EH2+1AW',
    wazeUrl: 'https://waze.com/ul?ll=55.9547,-3.1911&navigate=yes',
    scheduleDeponere: 'Luni–Joi 09:00–16:00 · Vineri 09:00–12:00 · cu programare',
    scheduleRidicare: 'Luni–Joi 15:00–17:00 (fără programare prealabilă pentru pașapoarte gata)',
    schedulePassportPickup: 'Luni–Joi 15:00–17:00 (fără programare prealabilă)',
    schedulePassportPickupCrds: 'Ridicare la ghișeu · opțiunea prin poștă nu este confirmată',
    schedulePassportPickupStandard: 'Luni–Joi 15:00–17:00 (fără programare prealabilă)',
    scheduleTitluCalatorie: 'Fără programare dacă dovedești plecare în max 7 zile lucrătoare',
    scheduleTravelDoc: 'Fără programare dacă dovedești plecare în max 7 zile lucrătoare',
    paymentMethod: 'numerar sau card bancar',
    paymentPassport: '~52 GBP · numerar sau card · taxa variază lunar',
    paymentPassportCrds: '~52 GBP · numerar sau card · taxa variază lunar',
    paymentPassportTemporary: '~18 GBP · numerar sau card · taxa variază lunar',
    paymentNotarial: '0 GBP fără incidență / 3 GBP cu incidență + 4 GBP verificare CNARNN',
    paymentPassportNote: 'Edinburgh are grilă proprie de taxe. Verifică suma exactă pe site, fiind variabilă lunar.',
    paymentPassportCrdsNote: 'Edinburgh are grilă proprie de taxe pentru pașaportul CRDS. Verifică suma exactă pe site, fiind variabilă lunar.',
    paymentPassportTemporaryNote: 'Edinburgh are taxă separată pentru pașaport temporar, semnificativ mai mică decât pașaportul electronic. Verifică suma exactă pe site.',
    paymentNotarialNote: 'Edinburgh menționează și taxa CNARNN de 4 GBP pentru anumite verificări.',
    postalPickup: false,
    pasaportSearchUrl: 'https://edinburgh.mae.ro',
    staffShortageNotice: false,
    fotografiiLaGhiseu: true,
    starecivilaProgramRidicare: 'Verifică direct la consulat',
    starecivilaPosta: false,
    starecivilaTermen: 'în aceeași zi pentru minori sub 14 ani, dacă dosarul este complet',
  },
}
